/*
 * The User API
 *
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.9 cumulative-hardin
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.User.Api;
using Com.Lab5e.User.Model;
using Com.Lab5e.User.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.User.Test.Model
{
    /// <summary>
    ///  Class for testing AcceptInviteRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AcceptInviteRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AcceptInviteRequest
        //private AcceptInviteRequest instance;

        public AcceptInviteRequestTests()
        {
            // TODO uncomment below to create an instance of AcceptInviteRequest
            //instance = new AcceptInviteRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AcceptInviteRequest
        /// </summary>
        [Fact]
        public void AcceptInviteRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AcceptInviteRequest
            //Assert.IsType<AcceptInviteRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

    }

}
