/*
 * The User API
 *
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.10 constant-champ
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.User.Api;
using Com.Lab5e.User.Model;
using Com.Lab5e.User.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.User.Test.Model
{
    /// <summary>
    ///  Class for testing DeleteInviteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeleteInviteResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeleteInviteResponse
        //private DeleteInviteResponse instance;

        public DeleteInviteResponseTests()
        {
            // TODO uncomment below to create an instance of DeleteInviteResponse
            //instance = new DeleteInviteResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeleteInviteResponse
        /// </summary>
        [Fact]
        public void DeleteInviteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeleteInviteResponse
            //Assert.IsType<DeleteInviteResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Invite'
        /// </summary>
        [Fact]
        public void InviteTest()
        {
            // TODO unit test for the property 'Invite'
        }

    }

}
