/*
 * The User API
 *
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.6 crooked-daija
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.User.Api;
using Com.Lab5e.User.Model;
using Com.Lab5e.User.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.User.Test.Model
{
    /// <summary>
    ///  Class for testing InviteList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InviteListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InviteList
        //private InviteList instance;

        public InviteListTests()
        {
            // TODO uncomment below to create an instance of InviteList
            //instance = new InviteList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InviteList
        /// </summary>
        [Fact]
        public void InviteListInstanceTest()
        {
            // TODO uncomment below to test "IsType" InviteList
            //Assert.IsType<InviteList>(instance);
        }


        /// <summary>
        /// Test the property 'Invites'
        /// </summary>
        [Fact]
        public void InvitesTest()
        {
            // TODO unit test for the property 'Invites'
        }

    }

}
