/*
 * The User API
 *
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.4 breezy-leafy
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.User.Api;
using Com.Lab5e.User.Model;
using Com.Lab5e.User.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.User.Test.Model
{
    /// <summary>
    ///  Class for testing InviteRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InviteRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InviteRequest
        //private InviteRequest instance;

        public InviteRequestTests()
        {
            // TODO uncomment below to create an instance of InviteRequest
            //instance = new InviteRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InviteRequest
        /// </summary>
        [Fact]
        public void InviteRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" InviteRequest
            //Assert.IsType<InviteRequest>(instance);
        }


        /// <summary>
        /// Test the property 'TeamId'
        /// </summary>
        [Fact]
        public void TeamIdTest()
        {
            // TODO unit test for the property 'TeamId'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

    }

}
