/*
 * The User API
 *
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.11 lucky-fremont
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.User.Api;
using Com.Lab5e.User.Model;
using Com.Lab5e.User.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.User.Test.Model
{
    /// <summary>
    ///  Class for testing TeamList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TeamList
        //private TeamList instance;

        public TeamListTests()
        {
            // TODO uncomment below to create an instance of TeamList
            //instance = new TeamList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamList
        /// </summary>
        [Fact]
        public void TeamListInstanceTest()
        {
            // TODO uncomment below to test "IsType" TeamList
            //Assert.IsType<TeamList>(instance);
        }


        /// <summary>
        /// Test the property 'Teams'
        /// </summary>
        [Fact]
        public void TeamsTest()
        {
            // TODO unit test for the property 'Teams'
        }

    }

}
