/*
 * The User API
 *
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.7 frequent-amara
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.User.Api;
using Com.Lab5e.User.Model;
using Com.Lab5e.User.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.User.Test.Model
{
    /// <summary>
    ///  Class for testing Token
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Token
        //private Token instance;

        public TokenTests()
        {
            // TODO uncomment below to create an instance of Token
            //instance = new Token();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Token
        /// </summary>
        [Fact]
        public void TokenInstanceTest()
        {
            // TODO uncomment below to test "IsType" Token
            //Assert.IsType<Token>(instance);
        }


        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Fact]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }
        /// <summary>
        /// Test the property 'Write'
        /// </summary>
        [Fact]
        public void WriteTest()
        {
            // TODO unit test for the property 'Write'
        }
        /// <summary>
        /// Test the property '_Token'
        /// </summary>
        [Fact]
        public void _TokenTest()
        {
            // TODO unit test for the property '_Token'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'LastUse'
        /// </summary>
        [Fact]
        public void LastUseTest()
        {
            // TODO unit test for the property 'LastUse'
        }
        /// <summary>
        /// Test the property 'Uses'
        /// </summary>
        [Fact]
        public void UsesTest()
        {
            // TODO unit test for the property 'Uses'
        }

    }

}
