/*
 * The User API
 *
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.5 ceremonial-florie
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.User.Api;
using Com.Lab5e.User.Model;
using Com.Lab5e.User.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.User.Test.Model
{
    /// <summary>
    ///  Class for testing TokenList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenList
        //private TokenList instance;

        public TokenListTests()
        {
            // TODO uncomment below to create an instance of TokenList
            //instance = new TokenList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenList
        /// </summary>
        [Fact]
        public void TokenListInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenList
            //Assert.IsType<TokenList>(instance);
        }


        /// <summary>
        /// Test the property 'Tokens'
        /// </summary>
        [Fact]
        public void TokensTest()
        {
            // TODO unit test for the property 'Tokens'
        }

    }

}
