/*
 * The User API
 *
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.4 breezy-leafy
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.User.Api;
using Com.Lab5e.User.Model;
using Com.Lab5e.User.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.User.Test.Model
{
    /// <summary>
    ///  Class for testing UserProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserProfileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserProfile
        //private UserProfile instance;

        public UserProfileTests()
        {
            // TODO uncomment below to create an instance of UserProfile
            //instance = new UserProfile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserProfile
        /// </summary>
        [Fact]
        public void UserProfileInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserProfile
            //Assert.IsType<UserProfile>(instance);
        }


        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'AvatarUrl'
        /// </summary>
        [Fact]
        public void AvatarUrlTest()
        {
            // TODO unit test for the property 'AvatarUrl'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ProfileUrl'
        /// </summary>
        [Fact]
        public void ProfileUrlTest()
        {
            // TODO unit test for the property 'ProfileUrl'
        }
        /// <summary>
        /// Test the property 'GithubLogin'
        /// </summary>
        [Fact]
        public void GithubLoginTest()
        {
            // TODO unit test for the property 'GithubLogin'
        }
        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }
        /// <summary>
        /// Test the property 'LogoutUrl'
        /// </summary>
        [Fact]
        public void LogoutUrlTest()
        {
            // TODO unit test for the property 'LogoutUrl'
        }

    }

}
