/*
 * The User API
 *
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.10 constant-champ
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Lab5e.User.Client.OpenAPIDateConverter;

namespace Com.Lab5e.User.Model
{
    /// <summary>
    /// List of active invites. Onece an invite has been redeemed it will be removed automatically. An administrator of the team can delete unused invites.
    /// </summary>
    [DataContract(Name = "InviteList")]
    public partial class InviteList : IEquatable<InviteList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InviteList" /> class.
        /// </summary>
        /// <param name="invites">invites.</param>
        public InviteList(List<Invite> invites = default(List<Invite>))
        {
            this.Invites = invites;
        }

        /// <summary>
        /// Gets or Sets Invites
        /// </summary>
        [DataMember(Name = "invites", EmitDefaultValue = false)]
        public List<Invite> Invites { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InviteList {\n");
            sb.Append("  Invites: ").Append(Invites).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InviteList);
        }

        /// <summary>
        /// Returns true if InviteList instances are equal
        /// </summary>
        /// <param name="input">Instance of InviteList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InviteList input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Invites == input.Invites ||
                    this.Invites != null &&
                    input.Invites != null &&
                    this.Invites.SequenceEqual(input.Invites)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Invites != null)
                    hashCode = hashCode * 59 + this.Invites.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
